### ISSUE TITLE
Object search crash

### ISSUE THREAD

**Issue by hawesie** [kunzel/viper#1]
I think I sent it somehwhere stupid, but this shouldn't bring everything down.

```
[INFO] [WallTime: 1461929354.291509] Incoming service request: n: 10                                                                                                                                                                   [3/1915]
inflation_radius: 0.40000000596
roi: 
  points: 
    - 
      x: 0.677304446697
      y: 2.78514957428
      z: 0.0
    - 
      x: 0.759695529938
      y: 4.88783884048
      z: 0.0
    - 
      x: -1.72162413597
      y: 5.03976821899
      z: 0.0
    - 
      x: -1.72287154198
      y: 2.72014665604
      z: 0.0
[INFO] [WallTime: 1461929354.390274] ROI bounding box (meters): (-1.72287154198,2.72014665604) (0.759695529938,5.03976821899)
[INFO] [WallTime: 1461929354.390597] ROI bounding box (cells): (415,266) (465,312)
SOMETHING BAD HAPPEND!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERROR] [WallTime: 1461929354.406961] InvalidUserCodeError: Could not execute state 'ViewPlanning' of type '<viper_ros.view_planning.ViewPlanning object at 0x7f5a65add2d0>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/strands/tsc_ws/src/viper_ros/src/viper_ros/view_planning.py", line 221, in execute
    views = planner.sample_views_coverage_in_roi(NUM_OF_VIEWS, MIN_COVERAGE, octomap, octomap_keys)
  File "/home/strands/tsc_ws/src/viper/src/viper/core/planner.py", line 83, in sample_views_coverage_in_roi
    value = self._robot.evaluate(v, None) #octomap)
  File "/home/strands/tsc_ws/src/viper/src/viper/core/robot.py", line 26, in evaluate
    return self._view_evaluator.evaluate(view, octomap)
  File "/home/strands/tsc_ws/src/viper/src/viper/robots/scitos_simple.py", line 355, in evaluate
    req.pose = view.get_ptu_pose()
AttributeError: 'NoneType' object has no attribute 'get_ptu_pose'

        Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
InvalidUserCodeError: Could not execute state 'ViewPlanning' of type '<viper_ros.view_planning.ViewPlanning object at 0x7f5a65add2d0>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/strands/tsc_ws/src/viper_ros/src/viper_ros/view_planning.py", line 221, in execute
    views = planner.sample_views_coverage_in_roi(NUM_OF_VIEWS, MIN_COVERAGE, octomap, octomap_keys)
  File "/home/strands/tsc_ws/src/viper/src/viper/core/planner.py", line 83, in sample_views_coverage_in_roi
    value = self._robot.evaluate(v, None) #octomap)
  File "/home/strands/tsc_ws/src/viper/src/viper/core/robot.py", line 26, in evaluate
    return self._view_evaluator.evaluate(view, octomap)
  File "/home/strands/tsc_ws/src/viper/src/viper/robots/scitos_simple.py", line 355, in evaluate
    req.pose = view.get_ptu_pose()
AttributeError: 'NoneType' object has no attribute 'get_ptu_pose'

```

**Comment by kunzel** [comment]
It wasn;t able to sample enough robot poses in the specified region. And, yes, agreed, I will look into a better error handling.

**Comment by kunzel** [comment]
solved by https://github.com/kunzel/viper_ros/commit/cfb499e05d4c4c24660d7d2f32a432ebd71cfa40
