### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by hawesie** [kunzel/viper#2]
```
[INFO] [WallTime: 1461930148.875077] Found SURFACE ROI 12
[INFO] [WallTime: 1461930148.880310] State machine transitioning 'Setup':'succeeded'-->'ViewPlanning'
[INFO] [WallTime: 1461930148.885535] Point: [-12.651121139526367, 3.689558982849121]
[INFO] [WallTime: 1461930148.885892] Point: [-11.379740715026855, 3.6825952529907227]
[INFO] [WallTime: 1461930148.886228] Point: [-11.340032577514648, 5.456385612487793]
[INFO] [WallTime: 1461930148.886385] Point: [-12.407100677490234, 5.443490982055664]
[INFO] [WallTime: 1461930148.886542] Waiting for semantic map service
[INFO] [WallTime: 1461930148.889351] Done
[INFO] [WallTime: 1461930148.889963] Requesting octomap from semantic map service
[INFO] [WallTime: 1461930172.444341] Received octomap: size:3554025 resolution:0.05
[INFO] [WallTime: 1461930172.444750] Waiting for octomap set-octomap service
[INFO] [WallTime: 1461930172.447990] Done
[INFO] [WallTime: 1461930172.448349] Requesting to set octomap from set-octomap service
[ INFO] [1461930172.586830699]: Received service request: set_octomap
[ INFO] [1461930172.650183453]: Map received (710805 nodes, 0.050000 m res)
[ INFO] [1461930172.650481761]: Extracting supporting planes from octomap
[ INFO] [1461930173.171241265]: Extracted map size: 168914 (354780 free, and 64786 occupied leaf nodes were discarded)
[ INFO] [1461930173.171289789]: Finished service request.
[INFO] [WallTime: 1461930173.171538] Waiting for octomap get-keys service
[INFO] [WallTime: 1461930173.174691] Done
[INFO] [WallTime: 1461930173.174999] Requesting keys from octomap get-keys service
[ INFO] [1461930173.177339466]: Received service request: get_keys
[ INFO] [1461930173.218411769]: KEYS SIZE: 16969
[ INFO] [1461930173.218450284]: VALUES SIZE: 16969
[ INFO] [1461930173.218461642]: Finished service request.
[INFO] [WallTime: 1461930173.380653] Received octomap_keys: size:0
OCTOMAP KEYS []
[INFO] [WallTime: 1461930173.381055] Generate views.
[ERROR] [WallTime: 1461930173.384251] InvalidUserCodeError: Could not execute state 'ViewPlanning' of type '<viper_ros.view_planning.ViewPlanning object at 0x7f5aee020850>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/strands/tsc_ws/src/viper_ros/src/viper_ros/view_planning.py", line 221, in execute
    views = planner.sample_views_coverage_in_roi(NUM_OF_VIEWS, MIN_COVERAGE, octomap, octomap_keys)
  File "/home/strands/tsc_ws/src/viper/src/viper/core/planner.py", line 72, in sample_views_coverage_in_roi
    coverage = float(0) / len(octomap_keys)
ZeroDivisionError: float division by zero

Exception in thread Thread-50:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
InvalidUserCodeError: Could not execute state 'ViewPlanning' of type '<viper_ros.view_planning.ViewPlanning object at 0x7f5aee020850>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/strands/tsc_ws/src/viper_ros/src/viper_ros/view_planning.py", line 221, in execute
    views = planner.sample_views_coverage_in_roi(NUM_OF_VIEWS, MIN_COVERAGE, octomap, octomap_keys)
  File "/home/strands/tsc_ws/src/viper/src/viper/core/planner.py", line 72, in sample_views_coverage_in_roi
    coverage = float(0) / len(octomap_keys)
ZeroDivisionError: float division by zero

```

**Comment by kunzel** [comment]
Ops, this shouldn't happen. 
I think for some reason the octmap could not be retrieved...
"""
Received octomap_keys: size:0
OCTOMAP KEYS []
"""

**Comment by hawesie** [comment]
Still happening...

```
[INFO] [WallTime: 1463076057.889308] Done
[INFO] [WallTime: 1463076057.889709] Requesting keys from octomap get-keys service
[ INFO] [1463076057.893188307]: Received service request: get_keys
[ INFO] [1463076057.893959454]: KEYS SIZE: 1590
[ INFO] [1463076057.893976443]: VALUES SIZE: 1590
[ INFO] [1463076057.893990990]: Finished service request.
[INFO] [WallTime: 1463076057.914625] Received octomap_keys: size:0
OCTOMAP KEYS []
[INFO] [WallTime: 1463076057.915811] Generate views.
[ERROR] [WallTime: 1463076057.916082] InvalidUserCodeError: Could not execute state 'ViewPlanning' of type '<viper_ros.view_planning.ViewPlanning object at 0x7f3d00ddde10>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/strands/tsc_ws/src/viper_ros/src/viper_ros/view_planning.py", line 221, in execute
    views = planner.sample_views_coverage_in_roi(NUM_OF_VIEWS, MIN_COVERAGE, octomap, octomap_keys)
  File "/home/strands/tsc_ws/src/viper/src/viper/core/planner.py", line 72, in sample_views_coverage_in_roi
    coverage = float(0) / len(octomap_keys)
ZeroDivisionError: float division by zero

Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
InvalidUserCodeError: Could not execute state 'ViewPlanning' of type '<viper_ros.view_planning.ViewPlanning object at 0x7f3d00ddde10>': Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/strands/tsc_ws/src/viper_ros/src/viper_ros/view_planning.py", line 221, in execute
    views = planner.sample_views_coverage_in_roi(NUM_OF_VIEWS, MIN_COVERAGE, octomap, octomap_keys)
  File "/home/strands/tsc_ws/src/viper/src/viper/core/planner.py", line 72, in sample_views_coverage_in_roi
    coverage = float(0) / len(octomap_keys)
ZeroDivisionError: float division by zero
```

**Comment by kunzel** [comment]
solved by https://github.com/kunzel/viper_ros/commit/cfb499e05d4c4c24660d7d2f32a432ebd71cfa40
